import { StyleSheet } from 'react-native';

/**
 * This file contains the styles used in the application.
 * It defines styles for various components such as containers, buttons, text, and modals.
 * The styles are created using React Native's StyleSheet API.
 */
export default StyleSheet.create({
  container: { flex: 1, padding: 20, backgroundColor: '#f5f5f5' },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  headerContainer: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
  header: { fontSize: 24, fontWeight: 'bold', color: '#333' },
  addButton: { backgroundColor: '#007bff', borderRadius: 25, width: 50, height: 50, justifyContent: 'center', alignItems: 'center' },
  addButtonText: { color: '#fff', fontSize: 24, fontWeight: 'bold', lineHeight: 28 },
  tasksContainer: { flex: 1 },
  emptyState: { textAlign: 'center', color: '#888', marginTop: 20 },
  sectionHeader: { fontSize: 18, fontWeight: 'bold', marginTop: 20, marginBottom: 10, color: '#333' },
  overdueHeader: { color: '#ff4444', fontWeight: 'bold' },
  completedHeader: { color: '#888', fontWeight: 'bold' },
  taskItem: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#fff', padding: 15, borderRadius: 5, marginBottom: 10, shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.1, shadowRadius: 1, elevation: 1 },
  completedTask: { backgroundColor: '#f0f0f0' },
  overdueTask: { borderLeftWidth: 4, borderLeftColor: '#ff4444', backgroundColor: '#fff0f0' },
  checkbox: { padding: 0, margin: 0, marginRight: 10, backgroundColor: 'transparent', borderWidth: 0 },
  taskContent: { flex: 1 },
  taskTitle: { fontSize: 16, fontWeight: '500', marginBottom: 2 },
  taskMeta: { flexDirection: 'row', alignItems: 'center' },
  taskDate: { fontSize: 12, color: '#666', marginRight: 10 },
  taskDescriptionPreview: { fontSize: 12, color: '#666', flex: 1 },
  completedTaskText: { textDecorationLine: 'line-through', color: '#888' },
  overdueText: { color: '#ff4444', fontWeight: 'bold' },
  taskActions: { flexDirection: 'row', gap: 15, marginLeft: 10 },
  modalOverlay: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(0, 0, 0, 0.5)' },
  modalContent: { width: '90%', backgroundColor: '#fff', borderRadius: 10, padding: 20 },
  modalTitle: { fontSize: 20, fontWeight: 'bold', marginBottom: 15, color: '#333' },
  editInput: { borderWidth: 1, borderColor: '#ddd', borderRadius: 5, padding: 10, marginBottom: 15, backgroundColor: '#fff' },
  editDescriptionInput: { minHeight: 100 },
  datePickerButton: { flexDirection: 'row', alignItems: 'center', padding: 10, borderWidth: 1, borderColor: '#ddd', borderRadius: 5, marginBottom: 15 },
  datePickerText: { marginLeft: 10, color: '#007bff' },
  modalButtons: { flexDirection: 'row', justifyContent: 'flex-end', gap: 10 },
  cancelButton: { padding: 10 },
  cancelButtonText: { color: '#888' },
  saveButton: { backgroundColor: '#007bff', borderRadius: 5, padding: 10 },
  saveButtonDisabled: { opacity: 0.5 },
  saveButtonText: { color: '#fff' },
  detailsModal: { width: '90%', backgroundColor: '#fff', borderRadius: 10, padding: 20, paddingTop: 40 },
  closeButton: { position: 'absolute', top: 10, right: 10, padding: 5 },
  detailsTitle: { fontSize: 22, fontWeight: 'bold', marginBottom: 10, color: '#333' },
  detailsDate: { fontSize: 14, color: '#666', marginBottom: 15 },
  detailsDescription: { fontSize: 16, lineHeight: 24, color: '#555', marginBottom: 20 },
  noDescription: { fontSize: 16, color: '#999', fontStyle: 'italic', marginBottom: 20 },
  detailsActions: { flexDirection: 'row', justifyContent: 'space-between', borderTopWidth: 1, borderTopColor: '#eee', paddingTop: 15 },
  detailsActionButton: { flexDirection: 'row', alignItems: 'center', padding: 10 },
  deleteActionButton: { marginLeft: 20 },
  detailsActionText: { marginLeft: 5, color: '#007bff' },
  deleteActionText: { color: '#ff4444' },
  confirmationModal: { width: '80%', backgroundColor: '#fff', borderRadius: 10, padding: 20, alignItems: 'center' },
  confirmationTitle: { fontSize: 20, fontWeight: 'bold', marginBottom: 10, color: '#333' },
  confirmationText: { fontSize: 16, marginBottom: 20, textAlign: 'center', color: '#555' },
  confirmationButtons: { flexDirection: 'row', justifyContent: 'space-between', width: '100%' },
  confirmationButton: { flex: 1, padding: 12, borderRadius: 5, alignItems: 'center' },
  cancelConfirmationButton: { backgroundColor: '#e0e0e0', marginRight: 10 },
  deleteConfirmationButton: { backgroundColor: '#ff4444' },
  confirmationButtonText: { color: '#fff', fontWeight: 'bold' },
});
