import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  mainHeader: { backgroundColor: '#007bff', paddingVertical: 15, paddingHorizontal: 20 },
  headerTitle: { fontSize: 28, color: '#fff' },
  bodyContainer: { flex: 1, backgroundColor: '#121212' },
  container: { padding: 20 },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  headerContainer: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
  header: { fontSize: 24, fontWeight: 'bold', color: '#fff' },
  addButton: { backgroundColor: '#1e88e5', borderRadius: 25, width: 50, height: 50, justifyContent: 'center', alignItems: 'center' },
  addButtonText: { color: '#fff', fontSize: 24, fontWeight: 'bold', lineHeight: 28 },
  tasksContainer: { flex: 1 },
  emptyState: { textAlign: 'center', color: '#bbb', marginTop: 20 },
  sectionHeader: { fontSize: 18, fontWeight: 'bold',  lineHeight: 20, color: '#eee' },
  overdueHeader: { color: '#ff6b6b', fontWeight: 'bold' },
  completedHeader: { color: '#888', fontWeight: 'bold' },
  taskItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1f1f1f',
    padding: 15,
    borderRadius: 5,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.3,
    shadowRadius: 2,
    elevation: 2,
  },
  sectionHeaderContainer: { flexDirection: 'row',alignItems: 'center',paddingVertical: 8, marginBottom: 10, marginTop: 20},
  sectionHeaderIcon: { marginRight: 8,},
  completedTask: { backgroundColor: '#2c2c2c' },
  overdueTask: { borderLeftWidth: 4, borderLeftColor: '#ff6b6b', backgroundColor: '#3a1f1f' },
  checkbox: { padding: 0, margin: 0, marginRight: 10, backgroundColor: 'transparent', borderWidth: 0 },
  taskContent: { flex: 1 },
  taskTitle: { fontSize: 16, fontWeight: '500', marginBottom: 2, color: '#ddd' },
  taskMeta: { flexDirection: 'row', alignItems: 'center' },
  taskDate: { fontSize: 12, color: '#aaa', marginRight: 10 },
  taskDescriptionPreview: { fontSize: 12, color: '#aaa', flex: 1 },
  completedTaskText: { textDecorationLine: 'line-through', color: '#666' },
  overdueText: { color: '#ff6b6b', fontWeight: 'bold' },
  taskActions: { flexDirection: 'row', gap: 15, marginLeft: 10 },
  modalOverlay: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(0, 0, 0, 0.7)' },
  modalContent: { width: '90%', backgroundColor: '#222', borderRadius: 10, padding: 20 },
  modalTitle: { fontSize: 20, fontWeight: 'bold', marginBottom: 15, color: '#fff' },
  editInput: { borderWidth: 1, borderColor: '#444', borderRadius: 5, padding: 10, marginBottom: 15, backgroundColor: '#333', color: '#eee' },
  editDescriptionInput: { minHeight: 100, color: '#eee' },
  datePickerButton: { flexDirection: 'row', alignItems: 'center', padding: 10, borderWidth: 1, borderColor: '#444', borderRadius: 5, marginBottom: 15 },
  datePickerText: { marginLeft: 10, color: '#42a5f5' },
  modalButtons: { flexDirection: 'row', justifyContent: 'flex-end', gap: 10 },
  cancelButton: { padding: 10 },
  cancelButtonText: { color: '#aaa' },
  saveButton: { backgroundColor: '#1e88e5', borderRadius: 5, padding: 10 },
  saveButtonDisabled: { opacity: 0.5 },
  saveButtonText: { color: '#fff' },
  detailsModal: { width: '90%', backgroundColor: '#222', borderRadius: 10, padding: 20, paddingTop: 40 },
  closeButton: { position: 'absolute', top: 10, right: 10, padding: 5 },
  detailsTitle: { fontSize: 22, fontWeight: 'bold', marginBottom: 10, color: '#fff' },
  detailsDate: { fontSize: 14, color: '#aaa', marginBottom: 15 },
  detailsDescription: { fontSize: 16, lineHeight: 24, color: '#ccc', marginBottom: 20 },
  noDescription: { fontSize: 16, color: '#777', fontStyle: 'italic', marginBottom: 20 },
  detailsActions: { flexDirection: 'row', justifyContent: 'space-between', borderTopWidth: 1, borderTopColor: '#444', paddingTop: 15 },
  detailsActionButton: { flexDirection: 'row', alignItems: 'center', padding: 10 },
  deleteActionButton: { marginLeft: 20 },
  detailsActionText: { marginLeft: 5, color: '#42a5f5' },
  deleteActionText: { color: '#ff6b6b' },
  confirmationModal: { width: '80%', backgroundColor: '#222', borderRadius: 10, padding: 20, alignItems: 'center' },
  confirmationTitle: { fontSize: 20, fontWeight: 'bold', marginBottom: 10, color: '#fff' },
  confirmationText: { fontSize: 16, marginBottom: 20, textAlign: 'center', color: '#ccc' },
  confirmationButtons: { flexDirection: 'row', justifyContent: 'space-between', width: '100%' },
  confirmationButton: { flex: 1, padding: 12, borderRadius: 5, alignItems: 'center' },
  cancelConfirmationButton: { backgroundColor: '#444', marginRight: 10 },
  deleteConfirmationButton: { backgroundColor: '#ff6b6b' },
  confirmationButtonText: { color: '#fff', fontWeight: 'bold' },
});
